In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%pylab inline
pylab.rcParams['figure.figsize'] = (10, 6)
color = sns.color_palette()

/usr/local/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')

Populating the interactive namespace from numpy and matplotlib

In [2]:
TARGET_LABELS = ['ind_ahor_fin_ult1', 'ind_aval_fin_ult1', 'ind_cco_fin_ult1',
 'ind_cder_fin_ult1', 'ind_cno_fin_ult1', 'ind_ctju_fin_ult1',
 'ind_ctma_fin_ult1', 'ind_ctop_fin_ult1', 'ind_ctpp_fin_ult1',
 'ind_deco_fin_ult1', 'ind_deme_fin_ult1', 'ind_dela_fin_ult1',
 'ind_ecue_fin_ult1', 'ind_fond_fin_ult1', 'ind_hip_fin_ult1',
 'ind_plan_fin_ult1', 'ind_pres_fin_ult1', 'ind_reca_fin_ult1',
 'ind_tjcr_fin_ult1', 'ind_valo_fin_ult1', 'ind_viv_fin_ult1',
 'ind_nomina_ult1', 'ind_nom_pens_ult1', 'ind_recibo_ult1']

Load data : 06/2015 and 07/2015

In [3]:
data_path = "data/"

In [4]:
train_month_06 = pd.read_csv(data_path+"train_2015-5.csv")
train_month_07 = pd.read_csv(data_path+"train_2015-7.csv")

/usr/local/lib/python2.7/site-packages/IPython/core/interactiveshell.py:2705: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

Number of clients :

In [5]:
print len(train_month_06['ncodpers'].unique()), len(train_month_07['ncodpers'].unique())

628354 829811

In [6]:
print train_month_06[TARGET_LABELS].sum().sum(), train_month_07[TARGET_LABELS].sum().sum()

1116964.0 1147954

In [7]:
train_month_06[TARGET_LABELS].describe()

,ind_ahor_fin_ult1,ind_aval_fin_ult1,ind_cco_fin_ult1,ind_cder_fin_ult1,ind_cno_fin_ult1,ind_ctju_fin_ult1,ind_ctma_fin_ult1,ind_ctop_fin_ult1,ind_ctpp_fin_ult1,ind_deco_fin_ult1,...,ind_hip_fin_ult1,ind_plan_fin_ult1,ind_pres_fin_ult1,ind_reca_fin_ult1,ind_tjcr_fin_ult1,ind_valo_fin_ult1,ind_viv_fin_ult1,ind_nomina_ult1,ind_nom_pens_ult1,ind_recibo_ult1
count,628354.000000,628354.000000,628354.000000,628354.000000,628354.000000,628354.000000,628354.000000,628354.000000,628354.000000,628354.000000,...,628354.000000,628354.000000,628354.000000,628354.000000,628354.000000,628354.000000,628354.000000,628354.000000,628354.000000,628354.000000
mean,0.000135,0.000033,0.778626,0.000498,0.100784,0.012149,0.011275,0.166928,0.056476,0.003270,...,0.007577,0.011705,0.003305,0.060867,0.057075,0.031745,0.005019,0.065847,0.067557,0.153463
std,0.011630,0.005781,0.415172,0.022313,0.301043,0.109552,0.105586,0.372912,0.230839,0.057094,...,0.086715,0.107556,0.057398,0.239086,0.231985,0.175320,0.070670,0.248014,0.250985,0.360433
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [17]:
train_month_07[TARGET_LABELS].describe()

,ind_ahor_fin_ult1,ind_aval_fin_ult1,ind_cco_fin_ult1,ind_cder_fin_ult1,ind_cno_fin_ult1,ind_ctju_fin_ult1,ind_ctma_fin_ult1,ind_ctop_fin_ult1,ind_ctpp_fin_ult1,ind_deco_fin_ult1,...,ind_hip_fin_ult1,ind_plan_fin_ult1,ind_pres_fin_ult1,ind_reca_fin_ult1,ind_tjcr_fin_ult1,ind_valo_fin_ult1,ind_viv_fin_ult1,ind_nomina_ult1,ind_nom_pens_ult1,ind_recibo_ult1
count,829811.000000,829811.000000,829811.000000,829811.000000,829811.000000,829811.000000,829811.000000,829811.000000,829811.000000,829811.000000,...,829811.000000,829811.000000,829811.000000,829811.000000,829811.000000,829811.000000,829811.000000,829811.000000,829811.000000,829811.000000
mean,0.000099,0.000023,0.607246,0.000386,0.074242,0.009137,0.008362,0.125677,0.042353,0.002223,...,0.005671,0.008851,0.002439,0.050348,0.044780,0.023739,0.003770,0.054153,0.059759,0.120485
std,0.009940,0.004785,0.488363,0.019634,0.262165,0.095150,0.091062,0.331485,0.201393,0.047100,...,0.075093,0.093665,0.049327,0.218661,0.206821,0.152235,0.061281,0.226320,0.237041,0.325528
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

Take a representative sample

In [8]:
df = train_month_07

In [9]:
df['logrenta'] = np.log(df[df['renta'] > 0]['renta'] + 1)
df.loc[df['logrenta'].isnull(), 'logrenta'] = -99
df = df.drop(['renta', 'antiguedad'], axis=1)

In [10]:
full_stats = df.describe()
full_stats

,ncodpers,age,ind_nuevo,indrel,ind_actividad_cliente,ind_ahor_fin_ult1,ind_aval_fin_ult1,ind_cco_fin_ult1,ind_cder_fin_ult1,ind_cno_fin_ult1,...,ind_plan_fin_ult1,ind_pres_fin_ult1,ind_reca_fin_ult1,ind_tjcr_fin_ult1,ind_valo_fin_ult1,ind_viv_fin_ult1,ind_nomina_ult1,ind_nom_pens_ult1,ind_recibo_ult1,logrenta
count,8.298110e+05,829811.000000,829811.000000,829811.000000,829811.000000,829811.000000,829811.000000,829811.000000,829811.000000,829811.000000,...,829811.000000,829811.000000,829811.000000,829811.000000,829811.000000,829811.000000,829811.000000,829811.000000,829811.000000,829811.000000
mean,8.035797e+05,40.464536,0.043316,1.168291,0.428964,0.000099,0.000023,0.607246,0.000386,0.074242,...,0.008851,0.002439,0.050348,0.044780,0.023739,0.003770,0.054153,0.059759,0.120485,9.686900
std,4.162197e+05,16.435557,0.203567,4.057616,0.494928,0.009940,0.004785,0.488363,0.019634,0.262165,...,0.093665,0.049327,0.218661,0.206821,0.152235,0.061281,0.226320,0.237041,0.325528,14.270897
min,1.588900e+04,18.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-99.000000
25%,4.364780e+05,25.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,11.147109
50%,8.970590e+05,40.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,11.498853
75%,1.166034e+06,50.000000,0.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,11.881648
max,1.423452e+06,90.000000,1.000000,99.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,17.179158

In [14]:
unique_ids   = pd.Series(df["ncodpers"].unique())
limit_people = 20000
unique_id    = unique_ids.sample(n=limit_people)
reduced_df = df[df.ncodpers.isin(unique_id)]
reduced_stats = reduced_df.describe()
reduced_stats

,ncodpers,age,ind_nuevo,indrel,ind_actividad_cliente,ind_ahor_fin_ult1,ind_aval_fin_ult1,ind_cco_fin_ult1,ind_cder_fin_ult1,ind_cno_fin_ult1,...,ind_plan_fin_ult1,ind_pres_fin_ult1,ind_reca_fin_ult1,ind_tjcr_fin_ult1,ind_valo_fin_ult1,ind_viv_fin_ult1,ind_nomina_ult1,ind_nom_pens_ult1,ind_recibo_ult1,logrenta
count,2.000000e+04,20000.000000,20000.000000,20000.000000,20000.000000,20000.0000,20000.0,20000.000000,20000.00000,20000.000000,...,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.00000,20000.000000
mean,7.984810e+05,40.552150,0.042400,1.205800,0.428000,0.0001,0.0,0.611800,0.00025,0.071850,...,0.009250,0.002600,0.048800,0.045000,0.024750,0.004000,0.052900,0.057500,0.11775,9.558725
std,4.172932e+05,16.452319,0.201505,4.486318,0.494801,0.0100,0.0,0.487353,0.01581,0.258246,...,0.095733,0.050925,0.215455,0.207309,0.155366,0.063121,0.223839,0.232801,0.32232,14.730466
min,1.597200e+04,18.000000,0.000000,1.000000,0.000000,0.0000,0.0,0.000000,0.00000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,-99.000000
25%,4.328408e+05,25.000000,0.000000,1.000000,0.000000,0.0000,0.0,0.000000,0.00000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,11.141113
50%,8.883230e+05,40.000000,0.000000,1.000000,0.000000,0.0000,0.0,1.000000,0.00000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,11.497013
75%,1.166417e+06,51.000000,0.000000,1.000000,1.000000,0.0000,0.0,1.000000,0.00000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,11.877900
max,1.423335e+06,90.000000,1.000000,99.000000,1.000000,1.0000,0.0,1.000000,1.00000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,17.179158

In [15]:
res = np.abs(full_stats - reduced_stats).drop(['count', '25%', '50%', '75%']).drop(['ncodpers'], axis=1)
print np.sum(res, axis=1)
print np.sum(np.sum(res, axis=1))
res

mean    0.281205
std     0.972684
min     0.000000
max     1.000000
dtype: float64
2.25388851457

,age,ind_nuevo,indrel,ind_actividad_cliente,ind_ahor_fin_ult1,ind_aval_fin_ult1,ind_cco_fin_ult1,ind_cder_fin_ult1,ind_cno_fin_ult1,ind_ctju_fin_ult1,...,ind_plan_fin_ult1,ind_pres_fin_ult1,ind_reca_fin_ult1,ind_tjcr_fin_ult1,ind_valo_fin_ult1,ind_viv_fin_ult1,ind_nomina_ult1,ind_nom_pens_ult1,ind_recibo_ult1,logrenta
mean,0.087614,0.000916,0.037509,0.000964,0.000001,0.000023,0.004554,0.000136,0.002392,0.000237,...,0.000399,0.000161,0.001548,0.000220,0.001011,0.00023,0.001253,0.002259,0.002735,0.128175
std,0.016762,0.002062,0.428702,0.000127,0.000060,0.004785,0.001011,0.003824,0.003919,0.001229,...,0.002069,0.001598,0.003206,0.000488,0.003131,0.00184,0.002481,0.004239,0.003208,0.459570
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
max,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000

In [24]:
unique_ids   = pd.Series(df["ncodpers"].unique())
limit_people = 250000

print len(unique_ids), limit_people

counter = 200
found = False
tol = 0.1
while counter > 0 and not found:
    counter -= 1
    unique_id = unique_ids.sample(n=limit_people)
    reduced_df = df[df.ncodpers.isin(unique_id)]
    reduced_stats = reduced_df.describe()
    err = np.abs(full_stats - reduced_stats).drop(['count', '25%', '50%', '75%']).drop(['ncodpers'], axis=1)
    q = np.sum(np.sum(err, axis=1))
    print "counter : ", counter, " err = ", q
    if q < tol:
        found = True
    
assert found, "Failed to reduce"

reduced_stats

829811 250000
counter :  99  err =  0.232321040748
counter :  98  err =  0.197948023943
counter :  97  err =  0.404864004835
counter :  96  err =  0.13179471101
counter :  95  err =  0.165905476321
counter :  94  err =  0.105076618997
counter :  93  err =  0.14174951188
counter :  92  err =  0.190698650023
counter :  91  err =  0.665353191027
counter :  90  err =  0.145895807706
counter :  89  err =  0.121707092795
counter :  88  err =  0.130266865837
counter :  87  err =  0.191993893865
counter :  86  err =  0.127341990117
counter :  85  err =  1.24369101401
counter :  84  err =  0.396019868199
counter :  83  err =  0.145440165034
counter :  82  err =  0.247337084743
counter :  81  err =  0.36766029882
counter :  80  err =  0.314992526
counter :  79  err =  0.23896820921
counter :  78  err =  0.190940015295
counter :  77  err =  0.198233701971
counter :  76  err =  0.358604368371
counter :  75  err =  0.258083438883
counter :  74  err =  0.11213553349
counter :  73  err =  0.123378198085
counter :  72  err =  0.350818731492
counter :  71  err =  0.482795312508
counter :  70  err =  0.213648128476
counter :  69  err =  0.297823780758
counter :  68  err =  0.131403126318
counter :  67  err =  0.155041864295
counter :  66  err =  0.164562475222
counter :  65  err =  0.122400610669
counter :  64  err =  0.165144829608
counter :  63  err =  0.166497349384
counter :  62  err =  0.218918729204
counter :  61  err =  0.280353794228
counter :  60  err =  0.447233646227
counter :  59  err =  0.365942643556
counter :  58  err =  0.293468960387
counter :  57  err =  0.165274156637
counter :  56  err =  0.421022692668
counter :  55  err =  0.304247200273
counter :  54  err =  0.158694910486
counter :  53  err =  0.400957936564
counter :  52  err =  0.485837363344
counter :  51  err =  0.279713890815
counter :  50  err =  0.272759094247
counter :  49  err =  0.200180401002
counter :  48  err =  0.168423279217
counter :  47  err =  0.273874819564
counter :  46  err =  0.14115627696
counter :  45  err =  0.338851132265
counter :  44  err =  0.2019694909
counter :  43  err =  0.196670048939
counter :  42  err =  0.168246135597
counter :  41  err =  0.401210732742
counter :  40  err =  0.318658180562
counter :  39  err =  0.458169922938
counter :  38  err =  0.387714064277
counter :  37  err =  0.238970156314
counter :  36  err =  0.701952195229
counter :  35  err =  0.522925050069
counter :  34  err =  0.146678502082
counter :  33  err =  0.538667364188
counter :  32  err =  0.339998840623
counter :  31  err =  0.321803478044
counter :  30  err =  0.258004863132
counter :  29  err =  0.126353060302
counter :  28  err =  0.437039111655
counter :  27  err =  0.0674034364917

,ncodpers,age,ind_nuevo,indrel,ind_actividad_cliente,ind_ahor_fin_ult1,ind_aval_fin_ult1,ind_cco_fin_ult1,ind_cder_fin_ult1,ind_cno_fin_ult1,...,ind_plan_fin_ult1,ind_pres_fin_ult1,ind_reca_fin_ult1,ind_tjcr_fin_ult1,ind_valo_fin_ult1,ind_viv_fin_ult1,ind_nomina_ult1,ind_nom_pens_ult1,ind_recibo_ult1,logrenta
count,2.500000e+05,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,...,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000
mean,8.039199e+05,40.472044,0.043196,1.166208,0.428772,0.000112,0.000016,0.606180,0.000356,0.074572,...,0.008748,0.002420,0.050696,0.044808,0.023332,0.003756,0.054596,0.060280,0.120656,9.688164
std,4.161197e+05,16.434423,0.203298,4.032471,0.494902,0.010582,0.004000,0.488597,0.018865,0.262700,...,0.093121,0.049134,0.219377,0.206883,0.150956,0.061171,0.227190,0.238005,0.325728,14.259290
min,1.589000e+04,18.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-99.000000
25%,4.370310e+05,25.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,11.147109
50%,8.974370e+05,40.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,11.497897
75%,1.166230e+06,50.000000,0.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,11.881581
max,1.423443e+06,90.000000,1.000000,99.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,17.179158